version: "3.8"
services:
  postgres:
    image: postgres:16
    container_name: postgres16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST_AUTH_METHOD: trust # 개발 환경에서만 사용, 운영 환경에서는 적절한 인증 방법 사용 권장
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      # - ./postgres:/var/lib/postgresql/data  # 필요시 주석 해제
      # 최초 초기화 시 실행할 SQL 스크립트
      - ./initdb:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d stockdb"]
      interval: 3s
      timeout: 3s

volumes:
  pgdata: {}
