spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB:stock}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:pwd}
    hikari:
      initialization-fail-timeout: 0
  jpa:
    hibernate:
      ddl-auto: validate      # 스키마는 Flyway가 관리 → validate 권장
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    connect-retries: 10
    connect-retries-interval: 2s

finnhub:
  ws-url: ${FINHUB_WS_URL:wss://ws.finnhub.io}
  api-key: ${FINHUB_API_KEY}
  rest-url: ${FINNHUB_REST_URL:https://finnhub.io/api/v1}
